name: Create envfile

on: [push, workflow_dispatch]


jobs:

  create-envfile:
 
    runs-on: ubuntu-18.04
 
    steps:
    - name: Make envfile
      id: make
      uses: amalashkevich/create-envfile@v1
      with:
        envkey_DB_HOST: 'NEW_HOST'
        envkey_SOME_API_KEY: "123456abcdef"
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        some_other_variable: foobar
        template_file: .env.template1
        output_file_name: .env
    - name: Echo make
      run: echo "${{ steps.make.outputs.content }}"
    - name: Read package.json
      id: env
      uses: juliangruber/read-file-action@v1
      with:
        path: .env
    - name: Echo .env
      run: echo "${{ steps.env.outputs.content }}"
