name: Create envfile

on: [push, workflow_dispatch]


jobs:

  create-envfile:
 
    runs-on: ubuntu-18.04
 
    steps:
    - uses: actions/checkout@v2
    - name: Make envfile
      id: make
      uses: amalashkevich/create-envfile@master
      with:
        envkey_DB_HOST: 'NEW_HOST'
        envkey_DB_PASSWORD: ${{ secrets.SECRET_KEY }}
        envkey_SOME_API_KEY: "SOME_API_KEY_VALUE"
        envkey_SECRET_KEY: ${{ secrets.SECRET_KEY }}
        template_file: dir1/.env.template
        output_file: dir2/.env
    - name: Echo make
      run: echo "${{ steps.make.outputs.content }}"
    - name: Read package.json
      id: env
      uses: juliangruber/read-file-action@v1
      with:
        path: dir2/.env
    - name: Echo .env
      run: echo "${{ steps.env.outputs.content }}"
    - uses: shallwefootball/s3-upload-action@master
      with:
        aws_key_id: 'AKIAWXY3ZOSXOM7ZDNCA'
        aws_secret_access_key: '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'
        aws_bucket: 'viviparty'
        source_dir: 'dir2'
